[package]
name = "embeddings"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai"}
tokio = { version = "1.25.0", features = ["full"] }
dotenv = "0.15.0"
actix-web = "4"
serde_json = "1.0"
serde = "1.0.163"
